###
GET http://localhost:4004/odata/v4/catalog
Authorization: Basic erin:
###
GET http://localhost:4004/odata/v4/catalog/$metadata
Authorization: Basic erin:
###
GET http://localhost:4004/odata/v4/catalog/Books
#  ?$select=ID,title
Authorization: Basic erin:
###
POST http://localhost:4004/odata/v4/catalog/Books
Authorization: Basic erin:
Content-Type: application/json

{
  "ID": 3,
  "title": "Machts gut und danke für den Fisch",
  "stock": 500
}
