name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: pwd
        run: pwd
      - name: Install sapmachine
        run: |
          wget -qO- https://dist.sapmachine.io/debian/sapmachine.key | sudo tee /etc/apt/trusted.gpg.d/sapmachine.asc > /dev/null
          echo "deb https://dist.sapmachine.io/debian/$(dpkg --print-architecture)/ ./" | sudo tee /etc/apt/sources.list.d/sapmachine.list >/dev/null
          apt-get update
          apt-get install sapmachine-21-jdk
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Check node version
        run: node --version
      - name: Install MTA Build Tool
        run: npm install -g mbt
      - name: Install Packages
        shell: bash
        env:
          SAP_NPM_AUTH: ${{ secrets.SAP_NPM_AUTH }}
        run: npm install ci
      - name: MTA build
        uses: SAP/project-piper-action@master
        with:
          command: mtaBuild
      - name: Upload archive file
        uses: actions/upload-artifact@v3
        with:
          name: mta
          path: mtxs-bookshop.mtar
